---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: AWS Route53 hosted zone (wrapper)'
# cfn-modules:implements(HostedZone)
Parameters:
  Id:
    Description: 'The id of the hosted zone.'
    Type: String
Resources:
  HostedZoneDetailsFunctionPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 'route53:GetHostedZone'
          Resource: '*'
  HostedZoneDetailsFunction:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Handler: 'custom-resource.handler'
        Runtime: 'nodejs8.10'
        Timeout: '60'
        ManagedPolicyArns: !Ref HostedZoneDetailsFunctionPolicy
      TemplateURL: './node_modules/@cfn-modules/lambda-function/module.yml'
  HostedZoneDetails:
    Type: 'Custom::HostedZoneDetails'
    Version: '1.0'
    Properties:
      HostedZoneId: !Ref Id
      ServiceToken: !GetAtt 'HostedZoneDetailsFunction.Outputs.Arn'
Outputs:
  ModuleId:
    Value: 'route53-hosted-zone-wrapper'
  ModuleVersion:
    Value: '1.3.0'
  StackName:
    Value: !Ref 'AWS::StackName'
  Id:
    Value: !Ref Id
    Export:
      Name: !Sub '${AWS::StackName}-Id'
  Name:
    Value: !GetAtt 'HostedZoneDetails.Name'
    Export:
      Name: !Sub '${AWS::StackName}-Name'
